#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class StackPanel;
                ref class Pivot;
                ref class Button;
                ref class GridView;
                ref class TextBlock;
                ref class TextBox;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace MentorSystemUWP
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Image^ BackgroundImage;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ contentPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ drawingPanel;
        private: ::Windows::UI::Xaml::Controls::Pivot^ PivotPanel;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonExit;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonEraseAll;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonErase;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonPoints;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonLines;
        private: ::Windows::UI::Xaml::Controls::GridView^ TextsPanel;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage20;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage19;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage18;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage17;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage16;
        private: ::Windows::UI::Xaml::Controls::GridView^ HandsPanel;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage15;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage14;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage13;
        private: ::Windows::UI::Xaml::Controls::GridView^ ToolsPanel;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage12;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage11;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage10;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage9;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage8;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage7;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage6;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage5;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage4;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage3;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage2;
        private: ::Windows::UI::Xaml::Controls::Image^ iconPanelImage1;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ inputPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ greetingOutput;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ ColoredRectangle;
        private: ::Windows::UI::Xaml::Controls::TextBox^ nameInput;
        private: ::Windows::UI::Xaml::Controls::Button^ inputButton;
    };
}

