//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::MentorSystemUWP::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::MentorSystemUWP::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->BackgroundImage = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 2:
            {
                this->contentPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 3:
            {
                this->drawingPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 4:
            {
                this->PivotPanel = safe_cast<::Windows::UI::Xaml::Controls::Pivot^>(__target);
            }
            break;
        case 5:
            {
                this->buttonExit = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 6:
            {
                this->buttonEraseAll = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 7:
            {
                this->buttonErase = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 8:
            {
                this->buttonPoints = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 9:
            {
                this->buttonLines = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 10:
            {
                this->TextsPanel = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(__target);
            }
            break;
        case 11:
            {
                this->iconPanelImage20 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 12:
            {
                this->iconPanelImage19 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 13:
            {
                this->iconPanelImage18 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 14:
            {
                this->iconPanelImage17 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 15:
            {
                this->iconPanelImage16 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 16:
            {
                this->HandsPanel = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(__target);
            }
            break;
        case 17:
            {
                this->iconPanelImage15 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 18:
            {
                this->iconPanelImage14 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 19:
            {
                this->iconPanelImage13 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 20:
            {
                this->ToolsPanel = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(__target);
            }
            break;
        case 21:
            {
                this->iconPanelImage12 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 22:
            {
                this->iconPanelImage11 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 23:
            {
                this->iconPanelImage10 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 24:
            {
                this->iconPanelImage9 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 25:
            {
                this->iconPanelImage8 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 26:
            {
                this->iconPanelImage7 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 27:
            {
                this->iconPanelImage6 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 28:
            {
                this->iconPanelImage5 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 29:
            {
                this->iconPanelImage4 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 30:
            {
                this->iconPanelImage3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 31:
            {
                this->iconPanelImage2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 32:
            {
                this->iconPanelImage1 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->iconPanelImage1))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MentorSystemUWP::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TestFocusing);
            }
            break;
        case 33:
            {
                this->inputPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 34:
            {
                this->greetingOutput = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 35:
            {
                this->ColoredRectangle = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->ColoredRectangle))->DoubleTapped += ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::MentorSystemUWP::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&MainPage::Rectangle_DoubleTapped);
                (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->ColoredRectangle))->DragEnter += ref new ::Windows::UI::Xaml::DragEventHandler(this, (void (::MentorSystemUWP::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::DragEventArgs^))&MainPage::Rectangle_DragEntered);
            }
            break;
        case 36:
            {
                this->nameInput = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            }
            break;
        case 37:
            {
                this->inputButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->inputButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MentorSystemUWP::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::MentorSystemUWP::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


